# disable in production:  
local_backend: true
# command to run a local Decap instance: npx-decap-server

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/upload"
public_folder: "/"  

site_url: https://bianca-hambusch.netlify.app

media_library:
  name: cloudinary
  # output_filename_only: true
  config:
    cloud_name: dpkzi7ze1
    api_key: 838121396738531


# SEO anchor:
seo: &seo
  name: "SEOmetaData"
  label: "SEO"
  widget: "object"
  collapsed: true
  fields: 
    - { name: "metaTitle", label: "SEO Title", widget: "string", default: "{{ title }}", required: true }
    - { name: "metaDescription", label: "SEO Description", widget: "string", pattern: [".{10,160}", "between 20 and 160 characters"], required: true, hint: "must be between 20 and 160 characters" }
    - { name: "metaImage", label: "SEO image", widget: "image", default: "/images/logos/logo-hero.svg", hint: "image for social media sharing" }
    - { name: "keywords", label: "keywords", widget: "string", hint: "keywords are comma seperated", required: false }



collections:
  - name: "globalContent"
    label: "global content"
    files: 
      - label: "buttons"
        name: "buttons"
        file: "content/site/buttons.md"    
        fields: 
          - label: "next"
            name: "next"
            widget: "string"        
          - label: "previous"
            name: "previous"
            widget: "string"        
          - label: "close"
            name: "close"
            widget: "string"        
          - label: "article: more"
            name: "article"
            widget: "string"
            default: "read more"
          - label: "form: send"
            name: "send"
            widget: "string"
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "string", default: "Bianca Hambusch", hint: "Author of the blog post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: false, default: "{{date}}" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Kleingeschriebener URL-Teil, z. B. 'mein-erster-post'" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - *seo
      - { label: "Tags", name: "tags", widget: "list", hint: "Tags are comma separated", required: false, default: "blog" }
  # SINGLE PAGES
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/pages/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - *seo
      - name: "about"
        label: "about"
        file: "content/pages/about.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - *seo
      - name: "Kontakt"
        label: "contact"
        extension: json
        file: "content/pages/contact.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - *seo
      - name: "datenschutz"
        label: "datenschutz"
        file: "content/pages/datenschutz.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - *seo
      - name: "impressum"
        label: "impressum"
        file: "content/pages/impressum.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - *seo

          

